sudo: required
language: java
install:
  - true
env:
  - IDEA_VERSION=2016.3.7
  - IDEA_VERSION=2017.1.5
  - IDEA_VERSION=2017.2.6
  - IDEA_VERSION=2017.3.4
  - IDEA_VERSION=2018.1
os:
  - linux
  - osx

before_script: |
#Linux
if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
	sudo apt-get -qq update
	sudo add-apt-repository ppa:haxe/releases -y
	sudo apt-get update
	sudo apt-get install haxe -y
	mkdir ~/haxelib
	haxelib setup ~/haxelib
fi
#OSX
if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
	brew update
	brew install haxe
	mkdir ~/haxelib
	haxelib setup ~/haxelib
fi

script:
- ./gradlew clean BuildPlugin -PgenerateHxcpp=true -PtargetVersion=$IDEA_VERSION
- ./gradlew clean test -PgenerateHxcpp=true -PtargetVersion=$IDEA_VERSION


notifications:
email: false
