sudo: required
language: java
install:
  - true
env:
  - IDEA_VERSION=2016.3.7
  - IDEA_VERSION=2017.1.5
  - IDEA_VERSION=2017.2.6
  - IDEA_VERSION=2017.3.4
  - IDEA_VERSION=2018.1
os:
  - linux
  - osx
jdk:
  - oraclejdk8

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get -qq update                        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo add-apt-repository ppa:haxe/releases -y   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install haxe -y                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; mkdir ~/haxelib                                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; haxelib setup ~/haxelib                        ; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install haxe         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; mkdir ~/haxelib           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; haxelib setup ~/haxelib   ; fi

matrix:
  exclude:
  - os: osx
    jdk:
      - oraclejdk8

script:
- ./gradlew clean BuildPlugin -PgenerateHxcpp=true -PtargetVersion=$IDEA_VERSION
- ./gradlew clean test -PgenerateHxcpp=true -PtargetVersion=$IDEA_VERSION


notifications:
email: false
