sudo: required
language: java
jdk:
- oraclejdk8
before_script:
- sudo apt-get -qq update
- sudo add-apt-repository ppa:haxe/releases -y
- sudo apt-get update
- sudo apt-get install haxe -y
- mkdir ~/haxelib
- haxelib setup ~/haxelib
- haxelib install hxjava
- haxelib git hxcpp-debugger https://github.com/HaxeFoundation/hxcpp-debugger.git master
install:
- true
script: ./gradlew clean test -PtargetVersion=$IDEA_VERSION
env:
    - IDEA_VERSION=2016.3.7
    - IDEA_VERSION=2017.1.5
    - IDEA_VERSION=2017.2.6

notifications:
  email: false
