sudo: required
language: java
install:
  - true
env:
  - IDEA_VERSION=2016.3.7
  - IDEA_VERSION=2017.1.5
  - IDEA_VERSION=2017.2.6
  - IDEA_VERSION=2017.3.4
  - IDEA_VERSION=2018.1
os:
  - linux
  - osx

before_script:
# LINUX
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:haxe/releases -y   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install haxe -y                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ~/haxelib                                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then haxelib setup ~/haxelib                        ; fi
# OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install haxe         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir ~/haxelib           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then haxelib setup ~/haxelib   ; fi

script:
- ./gradlew clean BuildPlugin -PgenerateHxcpp=true -PtargetVersion=$IDEA_VERSION
- ./gradlew clean test -PgenerateHxcpp=true -PtargetVersion=$IDEA_VERSION


notifications:
email: false
