sudo: required
language: java
jdk:
- oraclejdk8
before_script:
- sudo apt-get -qq update
- sudo apt-get install ant-optional -y
- sudo add-apt-repository ppa:eyecreate/haxe -y
- sudo apt-get update
- sudo apt-get install haxe -y
- mkdir ~/haxelib
- haxelib setup ~/haxelib
- haxelib install hxjava
- haxelib install hxcpp-debugger
script: ./gradlew clean test -PtargetVersion=$IDEA_VERSION
env:
    - IDEA_VERSION=2016.3.7
    - IDEA_VERSION=2017.1.5
    - IDEA_VERSION=2017.2.6

notifications:
  email: false
