name: Build, IntelliJ-Haxe-plugin

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'

jobs:
  Build:
    strategy:
      fail-fast: false # set this to true if oyu want to cancel all builds if one fails.
      matrix:
        IDEA_VERSION: [2020.2, 2020.1.4,2019.3.5,2018.2.8,2017.3.5,2016.3.8]
        OS: [macOS-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
      - uses: actions/setup-java@v1
          with:
            java-version: 1.8

      - name: Set up Haxe
      - uses: krdlab/setup-haxe@v1
      with:
          haxe-version: 3.4.7
      - run: haxe -version

      - name: Build with Gradle
        run: gradle clean build verifyPlugin -PtargetVersion="${{ matrix.IDEA_VERSION }}"
